# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: posts.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'posts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bposts.proto\x12\x05posts\"Z\n\x11PostCreateRequest\x12\x10\n\x08owner_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0f\n\x07private\x18\x04 \x01(\x08\"*\n\x12PostCreateResponse\x12\x14\n\x0corder_status\x18\x01 \x01(\t2S\n\x0cPostsService\x12\x43\n\nCreatePost\x12\x18.posts.PostCreateRequest\x1a\x19.posts.PostCreateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'posts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSTCREATEREQUEST']._serialized_start=22
  _globals['_POSTCREATEREQUEST']._serialized_end=112
  _globals['_POSTCREATERESPONSE']._serialized_start=114
  _globals['_POSTCREATERESPONSE']._serialized_end=156
  _globals['_POSTSSERVICE']._serialized_start=158
  _globals['_POSTSSERVICE']._serialized_end=241
# @@protoc_insertion_point(module_scope)
